// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhachSan_fix.Data;

#nullable disable

namespace QuanLyKhachSan_fix.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("booking_code");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("date")
                        .HasColumnName("check_in_date");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("date")
                        .HasColumnName("check_out_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BookingCode")
                        .IsUnique()
                        .HasFilter("[booking_code] IS NOT NULL");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomerId");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.BookingDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<int?>("GuestCount")
                        .HasColumnType("int")
                        .HasColumnName("guest_count");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("RoomId");

                    b.ToTable("booking_details", (string)null);
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.BookingEditRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingDetailId")
                        .HasColumnType("int")
                        .HasColumnName("booking_detail_id");

                    b.Property<decimal?>("ExtraFee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("extra_fee");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("handled_at");

                    b.Property<int?>("HandledBy")
                        .HasColumnType("int")
                        .HasColumnName("handled_by");

                    b.Property<DateTime?>("NewCheckOutDate")
                        .HasColumnType("date")
                        .HasColumnName("new_check_out_date");

                    b.Property<int?>("NewRoomId")
                        .HasColumnType("int")
                        .HasColumnName("new_room_id");

                    b.Property<int?>("OldRoomId")
                        .HasColumnType("int")
                        .HasColumnName("old_room_id");

                    b.Property<string>("RequestType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("request_type");

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("requested_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BookingDetailId");

                    b.HasIndex("HandledBy");

                    b.HasIndex("NewRoomId");

                    b.HasIndex("OldRoomId");

                    b.ToTable("booking_edit_requests", (string)null);
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.Cancellation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<string>("CancelReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cancel_reason");

                    b.Property<decimal?>("CancellationFee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cancellation_fee");

                    b.Property<DateTime>("CancelledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("cancelled_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("ProcessedBy")
                        .HasColumnType("int")
                        .HasColumnName("processed_by");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("refund_amount");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ProcessedBy");

                    b.ToTable("cancellations", (string)null);
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.CheckIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingDetailId")
                        .HasColumnType("int")
                        .HasColumnName("booking_detail_id");

                    b.Property<DateTime>("CheckinTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("checkin_time")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("staff_id");

                    b.HasKey("Id");

                    b.HasIndex("BookingDetailId");

                    b.HasIndex("StaffId");

                    b.ToTable("checkins", (string)null);
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.CheckOut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingDetailId")
                        .HasColumnType("int")
                        .HasColumnName("booking_detail_id");

                    b.Property<DateTime>("CheckoutTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("checkout_time")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("staff_id");

                    b.HasKey("Id");

                    b.HasIndex("BookingDetailId");

                    b.HasIndex("StaffId");

                    b.ToTable("checkouts", (string)null);
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("hire_date");

                    b.Property<string>("Position")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("position");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salary");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("issued_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("IssuedBy")
                        .HasColumnType("int")
                        .HasColumnName("issued_by");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("IssuedBy");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("payment_status");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("Floor")
                        .HasColumnType("int")
                        .HasColumnName("floor");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("room_number");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int")
                        .HasColumnName("room_type_id");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.HasIndex("RoomTypeId");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BasePrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_price");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("MaxCapacity")
                        .HasColumnType("int")
                        .HasColumnName("max_capacity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("room_types", (string)null);
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.Booking", b =>
                {
                    b.HasOne("QuanLyKhachSan_fix.Models.User", "CreatedByUser")
                        .WithMany("BookingsCreated")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyKhachSan_fix.Models.User", "Customer")
                        .WithMany("BookingsAsCustomer")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.BookingDetail", b =>
                {
                    b.HasOne("QuanLyKhachSan_fix.Models.Booking", "Booking")
                        .WithMany("BookingDetails")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan_fix.Models.Room", "Room")
                        .WithMany("BookingDetails")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.BookingEditRequest", b =>
                {
                    b.HasOne("QuanLyKhachSan_fix.Models.BookingDetail", "BookingDetail")
                        .WithMany("EditRequests")
                        .HasForeignKey("BookingDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan_fix.Models.User", "HandledByUser")
                        .WithMany("BookingEditRequestsHandled")
                        .HasForeignKey("HandledBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyKhachSan_fix.Models.Room", "NewRoom")
                        .WithMany("EditRequestsAsNewRoom")
                        .HasForeignKey("NewRoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyKhachSan_fix.Models.Room", "OldRoom")
                        .WithMany("EditRequestsAsOldRoom")
                        .HasForeignKey("OldRoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BookingDetail");

                    b.Navigation("HandledByUser");

                    b.Navigation("NewRoom");

                    b.Navigation("OldRoom");
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.Cancellation", b =>
                {
                    b.HasOne("QuanLyKhachSan_fix.Models.Booking", "Booking")
                        .WithMany("Cancellations")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan_fix.Models.User", "ProcessedByUser")
                        .WithMany("CancellationsProcessed")
                        .HasForeignKey("ProcessedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Booking");

                    b.Navigation("ProcessedByUser");
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.CheckIn", b =>
                {
                    b.HasOne("QuanLyKhachSan_fix.Models.BookingDetail", "BookingDetail")
                        .WithMany("CheckIns")
                        .HasForeignKey("BookingDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan_fix.Models.User", "Staff")
                        .WithMany("CheckInsPerformed")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookingDetail");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.CheckOut", b =>
                {
                    b.HasOne("QuanLyKhachSan_fix.Models.BookingDetail", "BookingDetail")
                        .WithMany("CheckOuts")
                        .HasForeignKey("BookingDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan_fix.Models.User", "Staff")
                        .WithMany("CheckOutsPerformed")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookingDetail");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.Employee", b =>
                {
                    b.HasOne("QuanLyKhachSan_fix.Models.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("QuanLyKhachSan_fix.Models.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.Invoice", b =>
                {
                    b.HasOne("QuanLyKhachSan_fix.Models.Booking", "Booking")
                        .WithMany("Invoices")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan_fix.Models.User", "IssuedByUser")
                        .WithMany("InvoicesIssued")
                        .HasForeignKey("IssuedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Booking");

                    b.Navigation("IssuedByUser");
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.Notification", b =>
                {
                    b.HasOne("QuanLyKhachSan_fix.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.Payment", b =>
                {
                    b.HasOne("QuanLyKhachSan_fix.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.Room", b =>
                {
                    b.HasOne("QuanLyKhachSan_fix.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.Booking", b =>
                {
                    b.Navigation("BookingDetails");

                    b.Navigation("Cancellations");

                    b.Navigation("Invoices");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.BookingDetail", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("CheckOuts");

                    b.Navigation("EditRequests");
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.Room", b =>
                {
                    b.Navigation("BookingDetails");

                    b.Navigation("EditRequestsAsNewRoom");

                    b.Navigation("EditRequestsAsOldRoom");
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("QuanLyKhachSan_fix.Models.User", b =>
                {
                    b.Navigation("BookingEditRequestsHandled");

                    b.Navigation("BookingsAsCustomer");

                    b.Navigation("BookingsCreated");

                    b.Navigation("CancellationsProcessed");

                    b.Navigation("CheckInsPerformed");

                    b.Navigation("CheckOutsPerformed");

                    b.Navigation("Employee");

                    b.Navigation("InvoicesIssued");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
